[workspace]
resolver = "2"
members = [
    "cobalt_backend/cloud", "cobalt_backend/sync", 
    "cobalt_cloud",
    "cobalt_ai", "cobalt_ai/experiments/scratch_model",
    "cobalt_systems/userland/minigrep", "cobalt_embedded",
    "cobalt_frontend/app/encrypt_notepad/notepad/native", "examples/test_code_rust", "cobalt_backend/sync", "cobalt_studio", "cobalt_shared",
]

[workspace.dependencies.axum]
version = "0.8.8"
features = ["multipart", "tracing"]

[workspace.dependencies.tokio]
version = "1"
features = ["full"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
