[application]
name = "cobalt-cloud"
default_platform = "desktop"
out_dir = "dist"

[web]
app = { title = "Cobalt Cloud - Your Room HDD Cloud" }
assets_dir = "."          # ← add this line

# [web.assets]
# style = ["./tailwind.css"]